### ISSUE TITLE
Typescript error: implicit "any"

### ISSUE THREAD

**Issue by FrozenKiwi** [react-boilerplate/redux-injectors#12]
```
ERROR in C:/src/TheCoin/node_modules/redux-injectors/index.d.ts(16,17):
TS7010: 'forceReducerReload', which lacks return-type annotation, implicitly has an 'any' return type.
```

Sure enough, what I have is:
```export function forceReducerReload(store: {});```

I'd really like to have this compiler option turned on, as it can catch quite a few genuine bugs, but this issue is preventing me at the moment.

I'd be happy to open a PR, but I don't see where your TS types come from (only JS in this repo?)

**Comment by BenLorantfy** [comment]
Fixed in https://github.com/react-boilerplate/redux-injectors/pull/13
