### ISSUE TITLE
Feature Request: useInjectSagas ie useInjectSaga for multiple sagas

### ISSUE THREAD

**Issue by sbue** [react-boilerplate/redux-injectors#21]
Given a functional component, I would like the ability to use multiple sagas.

An example of this may be a settings page where button1 dispatches action1 and button2 dispatches action2. These actions would correspond to different sagas.

Alternatively, what is another way of doing this? Would it be the code below?
```
export function* settingsPageSaga() {
  yield takeLatest(actions.action1.type, functionForAction1);
  yield takeLatest(actions.action2.type, functionForAction2);
}
```

**Comment by BenLorantfy** [comment]
I'd recommend the code you have above, it ends up being easier to manage sagas IMO

**Comment by sbue** [comment]
Got it thanks 👍

**Comment by BenLorantfy** [comment]
Also you should be able to call `useInjectSaga` multiple times in one function

**Comment by sbue** [comment]
@BenLorantfy I've tried this out - using `useInjectSaga` for two sagas that correspond to the same reducerKey. For example:

```
export function GithubRepoForm() {
  useInjectReducer({ key: sliceKey, reducer: reducer });
  useInjectSaga({ key: sliceKey, saga: githubRepoFormSaga });
  useInjectSaga({ key: sliceKey, saga: githubRepoFormSaga2 });
```

In this case, only `githubRepoFormSaga2` works and `githubRepoFormSaga` is overwritten

**Comment by BenLorantfy** [comment]
you'd have to use a different key.  In this case I'd combine them, each slice should only have one saga IMO, but if you want to inject sagas from different slices you can use `useInjectSaga` with different slice keys.
