### ISSUE TITLE
Persist state of redux

### ISSUE THREAD

**Issue by AleXzpm** [react-boilerplate/redux-injectors#23]
Using redux-injectors makes it imposible to persist the state because the injectorsEnhancer regularly replaces the rootReducer with a new one - and only the initial one of those is persisted. Am I wrong? How  can we persist the state of redux? 
![image](https://user-images.githubusercontent.com/13512048/115973069-089c4c80-a55b-11eb-8618-bbeeda1acb46.png)
![image](https://user-images.githubusercontent.com/13512048/115973075-181b9580-a55b-11eb-9840-ef81400f7679.png)

**Comment by siarheipashkevich** [comment]
@AleXzpm hi, did you find the solution?

**Comment by BenLorantfy** [comment]
`redux-persist` has a [piece of documentation](https://github.com/rt2zz/redux-persist/blob/master/docs/hot-module-replacement.md) that implies one needs to call `persistReducer` every time they call `replaceReducer`.  Since we call `replaceReducer` internally within this library, it's not possible to use `redux-persist` currently.

We could probably add a mechanism for allowing this.  Maybe some kind of hook `onReplaceReducer` or something.  I'll try to find some time to look into this.

**Comment by siarheipashkevich** [comment]
@BenLorantfy thank you, and could please investigate how we can use immer with you library?

**Comment by AleXzpm** [comment]
@siarheipashkevich no I did not, other then giving up on Injectors. Hopefully @BenLorantfy  can create some hook for this.

**Comment by BenLorantfy** [comment]
@siarheipashkevich immer should work fine with this library... were you running into any issues?

**Comment by BenLorantfy** [comment]
@AleXzpm I thought about this some more and I don't think this requires any changes in `redux-injectors`.  Something like this should work:

```
const createReducer = (injectedReducers) => {
  const combinedReducer = combineReducers(injectedReducers);
  const persistedReducer = persistReducer(persistConfig, combinedReducer);
  return persistedReducer;
}
```

The key is to move the `persistReducer` call into `createReducer`.  Lmk if that doesn't work for you.

**Comment by Pixel-Jack** [comment]
It worked for me thank you @BenLorantfy 🙏

**Comment by hellofantastic** [comment]
@BenLorantfy @Pixel-Jack 
Should that last solution work all the same if its dynamic  injectors like in [react-boilerplate-cra-template](https://github.com/react-boilerplate/react-boilerplate-cra-template)

```
import { combineReducers } from '@reduxjs/toolkit';

import { InjectedReducersType } from 'utils/types/injector-typings';

/**
 * Merges the main reducer with the router state and dynamically injected reducers
 */
export function createReducer(injectedReducers: InjectedReducersType = {}) {
  // Initially we don't have any injectedReducers, so returning identity function to avoid the error
  if (Object.keys(injectedReducers).length === 0) {
    return state => state;
  } else {
    return combineReducers({
      ...injectedReducers,
    });
  }
}
```

**Comment by hellofantastic** [comment]
EDIT, nope, need to refactor saga reducer wiring, store config, to include reducers/sagas statically for persisting and rehydrating for [react-boilerplate-cra-template](https://github.com/react-boilerplate/react-boilerplate-cra-template)
