### ISSUE TITLE
update to react 17

### ISSUE THREAD

**Issue by vospascal** [react-boilerplate/redux-injectors#26]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0" from redux-injectors@1.3.0
npm ERR! node_modules/redux-injectors
npm ERR!   redux-injectors@"*" from the root project

had to do this.. also react-boilerplate-cra still on version 16
```npm i redux-injectors --force```

**Comment by BenLorantfy** [comment]
This was fixed in https://github.com/react-boilerplate/redux-injectors/pull/28
