### ISSUE TITLE
Can I integrate to Next.Js?

### ISSUE THREAD

**Issue by cuongdevjs** [react-boilerplate/redux-injectors#37]

**Comment by cuongdevjs** [comment]
I love this library, but I don't know how to integrate it into next.js, because it differs too much. if yes, any documentation for this, please. Thank you

**Comment by BenLorantfy** [comment]
Hey @cuongdevjs , I don't think this library will work well with nextjs if you use server-side rendering.  Internally, it uses `useLayoutEffect` which does not run with server-side rendering.

If you use only client-side rendering, you should be able to follow the regular instructions here: https://github.com/react-boilerplate/redux-injectors#setting-up-the-redux-store

tbh I haven't tested it yet.  If you try setting it up, let me know how it goes.
