### ISSUE TITLE
Not able to get the store value

### ISSUE THREAD

**Issue by Aravindraj92** [react-boilerplate/redux-injectors#38]
I am trying to get the initial state values from the Store directly using

const store = createStore(reducer, composeEnhancers(
  ...
));
store.getState()

I am getting undefined

**Comment by BenLorantfy** [comment]
Hey @Aravindraj92 - I'm not quite sure I understand the question.  Can you elaborate further please?

Also if you can include a sample of what your reducer looks like, that would be helpful

**Comment by BenLorantfy** [comment]
Closing due to no response
