### ISSUE TITLE
How to create reducer with Immer ?

### ISSUE THREAD

**Issue by thaitanloi365** [react-boilerplate/redux-injectors#8]
Hi @BenLorantfy !

When I tried to create a reducer with Immer [https://github.com/immerjs/immer](url).

`const reducer = (state = initialState, action) => produce(state, draft => {
  switch (action.type) {
    case SIGNUP_REQUEST:
      draft.isFetching = true;
      break;
  }
})`

I got this error :
injectReducer: Expected `reducer` to be a reducer function

I think it shouldn't get the error.

Please help, thanks you.

**Comment by BenLorantfy** [comment]
hmm it should "just work"™ since your reducer is indeed a function. Can you share your redux store setup code?

**Comment by thaitanloi365** [comment]
Thanks for your response, I found the causes, now It's working.
